Presentation/Controllers/AdminProductController.cs
using DTO;
using Helper.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using Services;
using Services.Abstract;
using System.Diagnostics;

namespace Presentation.Controllers
{
    [Authorize(Roles = RoleKeywords.AdminRole)]
    public class AdminProductController : Controller
    {
        private readonly IProductService productService;

        public AdminProductController(IProductService productService)
        {
            this.productService = productService;
        }
       
        [HttpGet("{id}")]
        public IActionResult Update(int id)
        {
            var res = productService.Get(id);
            return View(res);
        }

        [HttpPost]
        public IActionResult UpdateDTO(ProductDTO product)
        {
            if (string.IsNullOrEmpty(product.ImgPath))
            {
                product.ImgPath = "~/img/pulp_fict.jpg";
            }
            var res = productService.Update(product);

            return View("Update",res);
        }

        [HttpGet]
        public IActionResult Add()
        { 
            return View();
        }

        [HttpPost]
        public IActionResult Add(ProductDTO product) 
        {
            if (string.IsNullOrEmpty(product.ImgPath)) 
            {
                product.ImgPath = "~/img/pulp_fict.jpg";
            }
            
            productService.Create(product);

            return View();
        }

        [HttpGet]
        public IActionResult GetAll(int page = 1, int pageSize = 4, ProductSortOrder order = ProductSortOrder.NameAsc, string search = null, bool changeSort = false)
        {
            if (!string.IsNullOrEmpty(search))
                ViewBag.Search = search;
            //to save search text in input

            int allProductsCount;
            var res = productService.GetFilter(out allProductsCount, page, pageSize, order, search);

            ViewBag.HasPrevious = true;
            ViewBag.HasNext = true;

            if (page <= 1)
            {
                ViewBag.HasPrevious = false;
            }
            if (page * pageSize >= allProductsCount)
            {
                ViewBag.HasNext = false;
            }

            if (changeSort)
            {
                ViewBag.NameSort = order == ProductSortOrder.NameAsc ? ProductSortOrder.NameDesc : ProductSortOrder.NameAsc;
                ViewBag.PriceSort = order == ProductSortOrder.PriceAsc ? ProductSortOrder.PriceDesc : ProductSortOrder.PriceAsc;
            }
            else
            {
                ViewBag.NameSort = order;
                ViewBag.PriceSort = order;
            }

            var pagedRs = new PagedResponseDTO<ProductDTO>(page, pageSize, res);

            return View(pagedRs);
        }

    }
}

Presentation/Controllers/LoginController.cs
using DTO;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Services.Abstract;
using System.Security.Claims;

namespace Presentation.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]       
        public IActionResult SignIn()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
                RedirectToAction("Index", "Home");

            return View();
        }

        [HttpPost]
        public IActionResult SignIn(UserDTO user)
        {
            try
            {
                user = _userService.Login(user);

                Authenticate(user);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }

        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(UserDTO user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _userService.Create(user);

                    ViewBag.Success = "User created!";
                    return View(user);
                }
                else
                    return View(user);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }

        }

        private void Authenticate(UserDTO user)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", user.Id.ToString()),
                new Claim("Username", user.Username),
                new Claim(ClaimTypes.Role, user.RoleName),
            };

            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie");

            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        [HttpGet]
        public IActionResult SignOut()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("SignIn");
        }

    }
}

Presentation/Controllers/ProductController.cs
using DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Abstract;
using System.Transactions;

namespace Presentation.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet("Product/Get/{id}")]
        public IActionResult Get(int id, string message = null, bool isSuccess = true)
        {
            if (!string.IsNullOrEmpty(message))
            {
                if (isSuccess)
                    ViewBag.Success = message;
                else
                    ViewBag.Error = message;
            }


            var res = _productService.Get(id);
            
            if (res == null)
            {
                ViewBag.Error = "Not Found!";
                return View();
            }
            return View(res);
        }

        [HttpGet]
        public IActionResult GetAll(int page = 1, int pageSize = 4, ProductSortOrder order = ProductSortOrder.NameAsc, string search = null,bool changeSort = false)
        {
            if (!string.IsNullOrEmpty(search))
                ViewBag.Search = search;
            //to save search text in input

            int allProductsCount;
            var res = _productService.GetFilter(out allProductsCount, page, pageSize, order, search);

            ViewBag.HasPrevious = true;
            ViewBag.HasNext = true;

            if (page <= 1)
            {
                ViewBag.HasPrevious = false;
            }
            if (page * pageSize >= allProductsCount)
            {
                ViewBag.HasNext = false;
            }

            if (changeSort)
            {
                ViewBag.NameSort = order == ProductSortOrder.NameAsc ? ProductSortOrder.NameDesc : ProductSortOrder.NameAsc;
                ViewBag.PriceSort = order == ProductSortOrder.PriceAsc ? ProductSortOrder.PriceDesc : ProductSortOrder.PriceAsc;
            }
            else
            {
                ViewBag.NameSort = order;
                ViewBag.PriceSort = order;
            }

            var pagedRs = new PagedResponseDTO<ProductDTO>(page, pageSize, res);

            return View(pagedRs);
        }

        [HttpPost]
        public IActionResult AddToCart(CartDTO dto)
        {
            bool isSuccess;
            string mes;
            try
            {
                dto.UserId = Convert.ToInt32(HttpContext.User.FindFirst(x => x.Type == "Id")?.Value);

                _productService.AddToCart(dto);
                mes = "Succesfuly added!";
                isSuccess = true;
            }
            catch (Exception ex)
            {
                mes = ex.Message;
                isSuccess = false;
            }

            return RedirectToAction("Get", 
                new { 
                    id = dto.ProductId,
                    message = mes,
                    isSuccess = isSuccess
                    });
        }

        [HttpGet]
        public IActionResult GetCart(string message = null, bool isSuccess = true)
        {
            if (!string.IsNullOrEmpty(message))
            {
                if (isSuccess)
                    ViewBag.Success = message;
                else
                    ViewBag.Error = message;
            }

            var userId = Convert.ToInt32(HttpContext.User.FindFirst(x => x.Type == "Id")?.Value);

            var res = _productService.GetCart(userId);
            
            return View(res);

        }

        [HttpPost]
        public IActionResult Buy(PayDTO dto) 
        {
            _productService.Buy(dto.CartId);

            return RedirectToAction("GetCart",
                new
                {
                    message = "Success! You paid " + dto.Sum + "$!",
                    isSuccess = true
                });
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int cartId)
        {
            _productService.DeleteFromCart(cartId);

            return RedirectToAction("GetCart",
                new
                {
                    message = "Success! Deleted from cart!",
                    isSuccess = true
                });
        }

    }
}

Presentation/Views/Shared/Message.cshtml
@{

    Layout = null;

    ViewBag.Show = "block";
    if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        ViewBag.Class = "alert-danger";
        ViewBag.Message = ViewBag.Error;
    }
    else if (!string.IsNullOrEmpty(ViewBag.Success))
    {
        ViewBag.Class = "alert-success";
        ViewBag.Message = ViewBag.Success;
    }
    else
    {
        ViewBag.Show = "none";
    }
}
<div class="mt-2 alert @ViewBag.Class .alert-dismissible fade show" style="display : @ViewBag.Show">
    <strong>@ViewBag.Message</strong>
    <button type="button" class="btn-close" style="float:right" data-bs-dismiss="alert"></button>
</div>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>

Presentation/Views/Shared/_Layout.cshtml
@using System.Globalization
@using System.Security.Claims
@using Helper.Constants
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentation.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="grad-bg">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presentation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="GetAll">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="GetCart">Cart</a>
                        </li>
                    </ul>
                    <p class="text-light mx-3 my-1">
                        Welcome @CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Context?.User?.FindFirst(x=>x.Type=="Username")?.Value ?? "")
                    </p>


                    @{
                        bool isAdmin = Context.User.IsInRole(RoleKeywords.AdminRole);
                      
                        <a style="display:@((isAdmin)? "block" :"none")" class="nav-link text-light btn btn-primary btn-p-8-16 mx-2" 
                        asp-controller="AdminProduct" asp-action="GetAll">Admin panel</a>
                    }
                    
                    <a class="nav-link text-light btn btn-danger btn-p-8-16" asp-area="" asp-controller="Login" asp-action="SignOut">Sign Out</a>

                </div>
            </div>
        </nav>
    </header>
    <div>
        <div class="container">
        <main role="main">
                @RenderBody()
        </main>
        </div>

    </div>
    
    <footer class="footer text-muted bg-dark mt-2">
        <div class="container text-light">
            &copy; 2022 - Presentation
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>